ci: set semantic release

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -1,18 +1,23 @@
 name: Checks
 
 on:
+  workflow_call:
   push:
     branches: [main]
   pull_request:
     types:
-      - synchronize # PR was updated
       - opened # PR was open
+      - synchronize # PR was updated
       - reopened # PR was closed and is now open again
       - ready_for_review # PR was converted from draft to open
+      - converted_to_draft # PR was converted from open to draft
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  group: checks_${{ github.workflow }}_${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
+
+permissions:
+  contents: read
 
 jobs:
   checks:
@@ -37,17 +42,22 @@ jobs:
       - name: Check Format
         run: pnpm format:check
 
-      # - name: Check Typing
+      # - name: Typecheck
+      #   if: success() || failure()
       #   run: pnpm typecheck
 
-      - name: Lint
-        run: pnpm lint
-
       - name: Lint Styles
+        if: success() || failure()
         run: pnpm lint:styles
 
+      - name: Lint
+        if: success() || failure()
+        run: pnpm lint
+
       # - name: Check Site build
+      #   if: success() || failure()
       #   run: pnpm build
 
       # - name: Check Lib pack
-      #   run: pnpm --filter logo-downloadtip prepack
+      #   if: success() || failure()
+      #   run: pnpm pack --recursive
